import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/themeprovider'
import { ModelProvider } from '@/components/providers/model-provider'
import { SocketProvider } from '@/components/providers/socket-proviter'
import { QueryProvider } from '@/components/providers/query-provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={(inter.className,
      "bg-white  dark:bg-[#313338]")}>
        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
        enableSystem={false}
        storageKey="discord_clone">
       <SocketProvider>
          <ModelProvider/>
        <QueryProvider>
        {children}
        </QueryProvider>
        </SocketProvider>
        </ThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  )
}
